import preparedGuides from './prepared-guides.json';
import {isPublished} from './publication.mjs';
import original from './original-services.json';
const additions={
 airway:{slug:'airway-sleep',title:'Airway & Sleep Concerns in Point Richmond',lead:'Start with your breathing concerns. Understand the right next step.',sections:[['Bring the whole picture','Tell us about mouth breathing, disrupted sleep, and any care you already receive. A written history helps the conversation stay focused on your concerns rather than a single symptom.'],['Understand the role of dental care','Oral observations can be part of the conversation about breathing and sleep. They do not establish a sleep apnea diagnosis. We discuss whether a medical or sleep evaluation is appropriate and how oral care may fit alongside it.'],['A coordinated next step','Bring relevant information from your other clinicians and ask what is within this practice’s scope. Any proposed oral-function work should fit your overall care plan. Continue prescribed treatment unless your treating clinician changes it.']],questions:[['Can this appointment diagnose sleep apnea?','No. Sleep apnea requires medical evaluation. This visit can help clarify oral concerns and questions to take to your medical clinician.'],['What should I bring?','Bring your questions, current medications, and relevant information about existing dental or sleep care.']],source:['NHLBI: Sleep apnea','https://www.nhlbi.nih.gov/health/sleep-apnea']},
 myofunctional:{slug:'myofunctional-therapy',title:'Myofunctional Therapy in Point Richmond',lead:'A thoughtful approach to tongue posture, swallowing, and oral habits.',sections:[['Understand your starting point','Describe the oral habits or functional concerns that brought you here. The conversation can include resting posture, lip closure, swallowing patterns, and how these show up in everyday life.'],['An individual plan','If therapy is appropriate, ask which goals are being addressed, how progress will be assessed, and what practice at home would involve. The plan should be understandable and realistic for you or your child.'],['Know how care fits together','Oral exercises are not a substitute for a medical diagnosis or prescribed sleep treatment. Discuss any orthodontic, dental, or medical care already underway so the next step can be coordinated.']],questions:[['Is this only for children?','The practice offers oral-function care for adults and children. Suitability and goals are individual.'],['Will exercises replace other treatment?','Do not assume so. Ask how the proposed work relates to your existing care and whether another clinician should be involved.']],source:['NHLBI: Sleep apnea treatment','https://www.nhlbi.nih.gov/health/sleep-apnea/treatment']},
 gums:{slug:'gum-care',title:'Gum Care & Dental Hygiene in Point Richmond',lead:'Bleeding or tender gums deserve an explanation you can understand.',sections:[['Discuss the changes you have noticed','Let us know about bleeding, tenderness, sensitivity, or changes in your daily routine. Include medications and previous dental treatment in the conversation. These details help inform an individual assessment.'],['Care matched to the findings','Plaque-related gum inflammation and more advanced gum disease are not the same situation. Professional care and home-care recommendations depend on the findings; some concerns need specialist evaluation.'],['Make the home routine practical','Bring the products and tools you currently use, or a list of them. Ask for a clear explanation of the routine recommended for your mouth and how follow-up will be decided.']],questions:[['Can I know what is wrong from bleeding alone?','No. Bleeding is a reason to arrange an assessment, not a diagnosis by itself.'],['Will every patient need the same cleaning?','Care depends on individual findings and history. Ask what is recommended, why, and what it involves before proceeding.']],source:['NIDCR: Periodontal disease','https://www.nidcr.nih.gov/health-info/gum-disease']},
 enamel:{slug:'enamel-remineralization',title:'Enamel & Cavity Prevention in Point Richmond',lead:'Understand what prevention can do—and when a tooth needs further care.',sections:[['A prevention conversation built around you','Your routine, dietary habits, saliva, medications, and dental history can all belong in a cavity-prevention discussion. Describe what you have noticed and what you hope to improve.'],['Early changes and established cavities differ','Some early mineral loss can improve with appropriate preventive care. A hole in a tooth cannot simply be brushed away. An assessment helps distinguish prevention needs from concerns requiring restorative care.'],['Choose products with a clear purpose','Ask what each recommendation is intended to do, how to use it, and what alternatives are available. No product should delay necessary dental assessment or treatment.']],questions:[['Does sensitivity always mean a cavity?','Sensitivity has different possible causes. An examination is needed to understand your situation.'],['Can a product rebuild a tooth with a hole?','Do not rely on that promise. Established cavities need a dental assessment and may require restoration.']],source:['NIDCR: Tooth decay','https://www.nidcr.nih.gov/health-info/tooth-decay']},
 ozone:{slug:'ozone-options',title:'Dental Ozone Options in Point Richmond',lead:'Make room for questions about evidence, alternatives, and the proposed use.',sections:[['Understand the intended role','The practice discusses ozone as an additional option in selected care plans. Ask what specific concern it would address and how it fits with established care.'],['Ask about evidence and limits','Evidence varies by proposed use. A published systematic review found insufficient, very-low-certainty evidence to recommend ozone for treating tooth decay. A clear discussion should include uncertainty as well as the intended benefit.'],['Make an informed choice','Ask about delivery, precautions, alternatives, and what happens if you decline. Ozone does not replace established cavity or gum treatment, and the practice does not present it as treatment for autoimmune disease.']],questions:[['Do I have to choose ozone to receive care?','Discuss your preferences and the alternatives available for your individual care plan.'],['Where can I read about the evidence?','The research review linked below is a starting point. Ask the practitioner how its findings relate to the specific proposed use.']],source:['Systematic review of ozone for caries','https://pubmed.ncbi.nlm.nih.gov/33303100/']},
 'whole-body':{slug:'preventive-care',title:'Preventive Dental Hygiene in Point Richmond',lead:'A personal routine. A broader conversation. A clear next step.',sections:[['Your history matters','Discuss daily habits, medications, previous dental care, and any changes you have noticed. The aim is to understand the context of your oral health and make recommendations that fit your life.'],['Prevention across different stages of life','Adults and children may need different support. Bring questions about comfort, routines, oral habits, and how to make home care manageable. Ask what follow-up is appropriate for your circumstances.'],['Work alongside your wider care team','Considering whole-person health does not mean replacing medical care. Oral concerns and general health can be related without proving that one treatment prevents a systemic condition.']],questions:[['What does whole-person care mean here?','It means considering your history and habits when discussing oral care, while explaining the limits of each recommendation.'],['Can I ask about products I already use?','Yes. Bring a list so the conversation can focus on your current routine and the purpose of any proposed changes.']],source:['NIDCR: Oral hygiene','https://www.nidcr.nih.gov/health-info/oral-hygiene']}
};
export const servicePages=original.map(s=>({...s,...additions[s.id],path:'/services/'+additions[s.id].slug+'/',kind:'service',description:s.text}));
export const navigation=[{label:'Care',href:'/services/'},{label:'Your first visit',href:'/first-visit/'},{label:'About',href:'/about/'},{label:'Patient guides',href:'/resources/'},{label:'Reviews',href:'/reviews/'},{label:'Visit us',href:'/point-richmond/'},{label:'Request a visit',href:'/contact/'}];
export const basePages=[
 {path:'/community/',title:'Instagram, Facebook & Practice Updates',description:'Connect with Pannu Holistic on Instagram and Facebook for the practice’s posts, updates, and community information.',kind:'community',lead:'A closer look at the people behind your care.'},
 {path:'/',title:'Holistic Dental Hygiene in Point Richmond | Pannu Holistic',description:'Personalized dental hygiene, myofunctional therapy, airway concerns, gum care, and prevention with Taren Pannu, RDHAP, BS in Point Richmond.'},
 {path:'/services/',title:'Dental Hygiene & Myofunctional Care',description:'Explore care for oral habits, airway concerns, gums, enamel, and prevention at Pannu Holistic in Point Richmond.',kind:'services',lead:'Find the care that starts with your concern.'},
 {path:'/about/',title:'Meet Taren Pannu, RDHAP, BS',description:'Meet Taren Pannu and explore the background, training, and preventive approach behind Pannu Holistic Dental Myology.',kind:'legacy',lead:'A personal approach to understanding your oral health.'},
 {path:'/first-visit/',title:'Your First Visit to Pannu Holistic',description:'Prepare for a visit to Pannu Holistic in Point Richmond: what to bring, questions to ask, and how to request an appointment.',kind:'first',lead:'Come with questions. Leave with a clearer next step.'},
 {path:'/products/',title:'Oral Care Products & Home Routines',description:'Explore the oral-care products listed by Pannu Holistic and ask which options fit your individual routine.',kind:'legacy',lead:'Keep the conversation going at home.'},
 {path:'/patient-stories/',title:'Patient Transformations & Care Journeys',description:'See the existing patient transformation photographs and individual care journeys from Pannu Holistic Dental Myology.',kind:'legacy',lead:'Individual people. Individual care journeys.'},
 {path:'/reviews/',title:'Patient Reviews of Pannu Holistic',description:'Read patient experiences, visit the original Google and Yelp review pages, and share your experience with Pannu Holistic.',kind:'reviews',lead:'Hear from people who have visited the practice.'},
 {path:'/point-richmond/',title:'Visit Pannu Holistic in Point Richmond',description:'Find Pannu Holistic at 229 Tewksbury Ave., Suite A, Point Richmond, CA 94801. Call 415.755.5549 or request an appointment.',kind:'location',lead:'Personal care, here in Point Richmond.'},
 {path:'/contact/',title:'Request an Appointment',description:'Request a visit with Pannu Holistic in Point Richmond. Call 415.755.5549 or send your contact details to the practice.',kind:'contact',lead:'Let’s find your next step together.'},
 {path:'/questions/',title:'Questions About Holistic Oral Care',description:'Explore the practice’s existing answers about gum care, enamel, oral-function work, and the evidence behind treatment options.',kind:'legacy',lead:'Good care makes room for good questions.'},
 {path:'/resources/',title:'Patient Guides & Visit Preparation',description:'Practical patient guides that connect your questions with the services, visit information, and appointment options at Pannu Holistic.',kind:'resources',lead:'Understand more. Feel better prepared.'},
 {path:'/privacy/',title:'Website Privacy Information',description:'How the Pannu Holistic website handles appointment requests, external services, and selected reviews.',kind:'privacy',lead:'Information about using this website.'},
 {path:'/terms/',title:'Website Terms & Information',description:'Information about educational content, appointment requests, third-party services, and patient stories on this website.',kind:'terms',lead:'Clear expectations for using the site.'}
];
const authored=[
 {slug:'prepare-your-first-visit',title:'Make the most of your first oral-care visit',description:'A simple way to organize your questions, current routine, and appointment details before visiting Pannu Holistic.',service:'preventive-care',publishOn:'2026-09-13',status:'approved',sections:[['Start with your main question','Write down the concern that matters most to you. You might want to discuss your cleaning routine, an oral habit, or how a proposed treatment fits with other care. A clear starting point helps you use the appointment well.'],['Bring useful context','Prepare a current medication list and the names of oral-care products you use. Note relevant dental care and the questions you would like answered. Ask the office ahead of time if there are specific records it needs.'],['Ask what happens next','Before leaving, make sure you understand the proposed next step, why it has been suggested, and whom to contact with questions. Ask about the expected cost and arrangements directly with the office rather than assuming coverage.']],checklist:['Choose your most important question.','Prepare your medication and product lists.','Confirm the visit details with the office.','Ask for an explanation of the next step.']},
 {slug:'questions-before-choosing-oral-care',title:'Questions to ask before choosing an oral-care option',description:'Use these practical questions to discuss purpose, alternatives, costs, and follow-up before making a care decision.',service:'preventive-care',publishOn:'2026-09-21',status:'approved',sections:[['Understand the purpose','Ask which concern a recommendation is intended to address and how that conclusion was reached. If a term is unfamiliar, ask for it to be explained in everyday language.'],['Explore the alternatives','Ask what other options are available, including what happens if you wait or decline. Discuss evidence and uncertainty with the practitioner rather than relying on a product label or someone else’s experience.'],['Clarify the practical details','Ask about fees, what the appointment involves, and whether follow-up is expected. Write down your questions before the visit so important details are not lost in the conversation.']],checklist:['Ask what the recommendation is intended to address.','Discuss alternatives and limitations.','Confirm fees with the office.','Know how to ask follow-up questions.']},
 {slug:'bring-your-home-care-routine',title:'Bring your home-care routine into the conversation',description:'Prepare a useful snapshot of your current oral-care products and habits so your next appointment starts with your real routine.',service:'gum-care',publishOn:'2026-09-28',status:'approved',sections:[['Make a quick list','Write down the names of the products and tools you currently use. A photograph of the labels may be easier than remembering everything during an appointment.'],['Describe what is realistic','Tell the practitioner what you find easy, confusing, or difficult about your current routine. The aim of this conversation is to make any recommended next steps understandable and practical.'],['Know the reason for a change','If a new product or tool is suggested, ask what it is for, how it would fit your routine, and what alternatives are available. Confirm any instructions with the practitioner before changing care based on general reading.']],checklist:['List current products and tools.','Note questions about your routine.','Explain any practical difficulties.','Ask why each change is recommended.']}
];
const generated=Object.values(import.meta.glob('./articles/*.json',{eager:true,import:'default'}));
export const allArticles=[...authored,...preparedGuides,...generated];
const today=import.meta.env.VITE_BUILD_DATE||'2026-09-13';
export const articles=allArticles.filter(g=>isPublished(g,today)).sort((a,b)=>b.publishOn.localeCompare(a.publishOn));
export const pages=[...basePages,...servicePages,...articles.map(g=>({...g,path:'/resources/'+g.slug+'/',kind:'article',lead:g.description}))];
export const getPage=path=>pages.find(p=>p.path===path)||{path,title:'Page not found',description:'Find your next step at Pannu Holistic.',kind:'404',lead:'Let’s help you find what you need.'};
