import React,{useState} from 'react';
import {articles,servicePages} from '../content/site.mjs';
import LegacySection from './LegacySection.jsx';
import ReviewTicker from './ReviewFeed.jsx';
import Community from './Community.jsx';
export const mapsUrl='https://www.google.com/maps/search/?api=1&query=Pannu+Holistic+Dental+Myology&query_place_id=ChIJUY5WJ9qDhYARJs7fpxLgji4';
const serviceFor=slug=>servicePages.find(s=>s.slug===slug);
export function ResourceCards({limit=100}){return <div className="resource-grid">{articles.slice(0,limit).map(a=><a className="resource-card" key={a.slug} href={'/resources/'+a.slug+'/'}><span className="eyebrow">PATIENT GUIDE · {a.publishOn}</span><h3>{a.title}</h3><p>{a.description}</p><span className="card-arrow">Read the guide ↗</span></a>)}</div>}
function CareCards({exclude}){return <div className="care-grid">{servicePages.filter(s=>s.slug!==exclude).map((s,i)=><a className="care-card" key={s.path} href={s.path}><span className="care-number">0{i+1}</span><h3>{s.title.replace(' in Point Richmond','')}</h3><p>{s.concern}</p><span className="card-arrow">Explore your options ↗</span></a>)}</div>}
function NextStep(){return <section className="next-step"><div className="container next-step-inner"><div><span className="eyebrow">YOUR NEXT STEP</span><h2>A conversation<br/>can bring clarity.</h2><p>Tell us what matters to you. We’ll help you understand where to begin.</p></div><a className="button button-light" href="/contact/">Request an appointment ↗</a></div></section>}
function ContactForm(){const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);if(data.get('website'))return;setBusy(true);setStatus('');data.append('_subject','Pannu website appointment request');data.append('_captcha','false');try{const r=await fetch(import.meta.env.VITE_CONTACT_ENDPOINT||'https://formsubmit.co/ajax/info@pannuholistic.com',{method:'POST',headers:{Accept:'application/json'},body:data,signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error();const result=await r.json();if(result.success!==true&&result.success!=='true')throw Error();setStatus('Your request was sent. The office will follow up to confirm availability.');form.reset();}catch{setStatus('Your request could not be sent. Your details remain here; please try again or call 415.755.5549.');}finally{setBusy(false)}}return <form className="visit-form" onSubmit={submit}><label>Your name<input name="name" autoComplete="name" required/></label><label>Email<input type="email" name="email" autoComplete="email" required/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required/></label><label>What would you like to discuss?<select name="interest" defaultValue=""><option value="">Select a topic (optional)</option>{servicePages.map(s=><option key={s.slug}>{s.title.replace(' in Point Richmond','')}</option>)}<option>Something else</option></select></label><label>Appointment message<textarea name="message" maxLength={2000} placeholder="Share your preferred callback time or a brief appointment question."/></label><input className="hp-field" tabIndex={-1} name="website" aria-hidden="true" autoComplete="off"/><p className="form-help">Please keep medical records and sensitive health details out of this form. A request does not confirm an appointment. <a href="/privacy/">Privacy information</a></p><button className="button button-primary" disabled={busy}>{busy?'Sending…':'Send appointment request ↗'}</button><p role="status">{status}</p></form>}
export default function Interior({page}){
const s=page.kind==='article'?serviceFor(page.service):page;
return <><header className="inside-hero"><div className="container"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span>{page.kind==='service'&&<><a href="/services/">Care</a><span>/</span></>}{page.kind==='article'&&<><a href="/resources/">Patient guides</a><span>/</span></>}<span>{page.kind==='article'?'Guide':page.title.replace(' in Point Richmond','')}</span></nav><span className="eyebrow">PANNU HOLISTIC · POINT RICHMOND</span><h1>{page.title}</h1><p>{page.lead}</p></div></header>
{page.kind==='services'&&<section className="section container"><CareCards/><div className="editorial-note"><h2>Not sure where to begin?</h2><p>Start with what you have noticed. You do not need to choose a treatment before contacting the office.</p><a href="/first-visit/">What to expect at your first visit ↗</a></div></section>}
{page.kind==='service'&&<><section className="section container service-layout"><aside className="care-sidebar"><span className="eyebrow">IN THIS GUIDE</span>{page.sections.map(([h],i)=><a key={h} href={'#care-'+i}>{h}</a>)}<a className="button button-primary" href="/contact/">Discuss your concerns ↗</a><a href="/first-visit/">Prepare for a first visit</a></aside><div className="reading-column"><p className="reading-lead">{page.text}</p>{page.sections.map(([h,p],i)=><section id={'care-'+i} key={h}><h2>{h}</h2><p>{p}</p></section>)}<h2>Questions you may have</h2><div className="patient-questions">{page.questions.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><p className="source-note">Further reading: <a href={page.source[1]} target="_blank" rel="noreferrer">{page.source[0]} ↗</a>. General information supports a conversation; individual care depends on assessment.</p></div></section><section className="section soft-band"><div className="container"><div className="section-head"><small>CONNECTED CARE</small><h2>Explore the bigger picture.</h2></div><CareCards exclude={page.slug}/></div></section></>}
{page.kind==='legacy'&&<LegacySection kind={page.path}/>}
{page.kind==='community'&&<Community/>}
{page.kind==='first'&&<section className="section container"><div className="first-visit-grid"><img src="/spa.jpg" alt="A calm setting for a conversation about your care"/><div className="reading-column"><span className="eyebrow">BEFORE · DURING · AFTER</span>{[['01 / Before your visit','Contact the office to discuss your concern and confirm appointment details. Ask about fees, payment arrangements, and any records to bring.'],['02 / Bring your questions','Prepare your medication list, information about current dental or medical care, and a list of products you use. Let the office know about accessibility or comfort needs before arriving.'],['03 / Understand the next step','Ask what is being recommended, why, what alternatives exist, and what follow-up may involve. You should have space to ask questions before choosing care.']].map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<a className="button button-primary" href="/contact/">Start with a conversation ↗</a></div></div><div className="editorial-note"><h2>Visiting with a child?</h2><p>Share comfort needs with the office in advance. The existing practice approach includes a calm environment, familiar entertainment, and encouragement without pressure.</p><a href="/#why-us">Explore the practice’s approach ↗</a></div></section>}
{page.kind==='reviews'&&<section className="section container"><div className="review-platforms"><a href={mapsUrl} target="_blank" rel="noreferrer"><span>GOOGLE</span><h2>Read current Google reviews ↗</h2><p>See the current rating and patient reviews on Google Maps.</p></a><a href="https://www.yelp.com/biz/pannu-holistic-dental-myology-point-richmond" target="_blank" rel="noreferrer"><span>YELP</span><h2>Read current Yelp reviews ↗</h2><p>Visit the practice’s Yelp page for the latest published experiences.</p></a></div><ReviewTicker/><div className="editorial-note"><h2>Your experience matters.</h2><p>Share an honest account of your visit. Reviews describe individual experiences and are not promises of treatment results.</p><div className="inline-actions"><a className="button button-primary" href="https://search.google.com/local/writereview?placeid=ChIJUY5WJ9qDhYARJs7fpxLgji4" target="_blank" rel="noreferrer">Write a Google review ↗</a><a href="https://www.yelp.com/biz/pannu-holistic-dental-myology-point-richmond" target="_blank" rel="noreferrer">Read reviews on Yelp ↗</a></div></div></section>}
{(page.kind==='contact'||page.kind==='location')&&<section className="section container visit-grid"><div><span className="eyebrow">FIND THE PRACTICE</span><h2>Point Richmond,<br/>California.</h2><p className="address">229 Tewksbury Ave. Ste A<br/>Point Richmond, CA 94801</p><a className="phone-link" href="tel:4157555549">415.755.5549</a><p>Contact the office for current appointment availability, fees, and access or arrival questions.</p><a className="care-link" href={mapsUrl} target="_blank" rel="noreferrer">Get directions in Google Maps ↗</a><div className="location-links"><a href="/first-visit/">Prepare for your first visit</a><a href="/services/">Explore services</a><a href="/about/">Meet Taren Pannu</a></div></div>{page.kind==='contact'?<ContactForm/>:<div className="location-panel"><img src="/spa.jpg" alt="A calm coastal setting"/><h3>One practice. A personal welcome.</h3><p>Based in Point Richmond, serving people from Richmond and the surrounding East Bay. Confirm travel and appointment arrangements directly with the office.</p><a className="button button-primary" href="/contact/">Request an appointment ↗</a></div>}</section>}
{page.kind==='resources'&&<section className="section container"><ResourceCards/><div className="editorial-note"><h2>Questions about treatment?</h2><p>Explore the service explanations and sources, then discuss your individual situation with the practice.</p><a href="/questions/">Read common care questions ↗</a></div></section>}
{page.kind==='article'&&<article className="section container article-layout"><aside className="care-sidebar"><p>Published <time dateTime={page.publishOn}>{page.publishOn}</time></p>{page.generated?<p>Reviewed by {page.reviewedBy}<br/>{page.reviewedOn}</p>:<p>Prepared for the Pannu Holistic patient library.</p>}<a href={s?.path||'/services/'}>Explore related care ↗</a><a href="/resources/">All patient guides</a></aside><div className="reading-column">{page.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<div className="editorial-note"><h2>Your next-step checklist</h2><ul>{page.checklist.map(c=><li key={c}>{c}</li>)}</ul></div>{page.sources?.length>0&&<div className="source-note"><h2>Sources & further reading</h2>{page.sources.map(x=><p key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.title} ↗</a></p>)}</div>}<p className="source-note">General patient education, prepared with AI assistance. Discuss treatment questions with your practitioner; this guide is not an individual assessment.</p></div></article>}
{page.kind==='privacy'&&<section className="section container reading-column legal-copy"><h2>Appointment requests</h2><p>The website asks for contact details so the office can respond to your appointment request. The form uses FormSubmit to deliver messages to info@pannuholistic.com. Please do not send medical records or detailed health information through this general inquiry form. Contact the office by phone to discuss an appropriate way to share those details.</p><h2>Google reviews and external services</h2><p>The website links to Google, Yelp, Instagram, and Facebook and includes a Google map on the homepage. These external services have their own privacy practices and may receive technical request information when used. The review cards on this site are a selected collection retained from the previous website; current reviews are available through the original platform links.</p><p><a href="https://policies.google.com/privacy">Google Privacy Policy</a> · <a href="https://formsubmit.co/privacy.pdf">FormSubmit privacy information</a></p><h2>Questions</h2><p>For questions about information sent to the practice, contact info@pannuholistic.com or call 415.755.5549. This page describes website functions; ask the practice directly about its clinical-record privacy practices.</p></section>}
{page.kind==='terms'&&<section className="section container reading-column legal-copy"><h2>Educational information</h2><p>Website content explains services and helps prepare for a conversation. It is not a diagnosis, an individual treatment plan, or a substitute for professional assessment. Patient photographs and reviews describe individual experiences, not expected results for everyone.</p><h2>Appointments and products</h2><p>An online request is not a confirmed booking. Confirm availability, fees, product suitability, and current arrangements directly with the office.</p><h2>Google Maps content</h2><p>Google Maps content is subject to <a href="https://maps.google.com/help/terms_maps/">Google Maps/Google Earth Additional Terms of Service</a> and <a href="https://policies.google.com/privacy">Google’s Privacy Policy</a>. Follow the source links to read or report reviews on Google.</p></section>}
{page.kind==='404'&&<section className="section container"><p>This address does not match a page on the site.</p><a className="button button-primary" href="/services/">Explore care ↗</a></section>}
{page.kind!=='contact'&&<NextStep/>}</>;
}
